[package]
name = "ssg"
version = "0.1.0"
edition = "2024"

[dependencies]
pulldown-cmark = "0.13.0"
ramhorns = "1.0.1"
clap = { version = "4.5.37", features = ["derive"] }
toml = "0.7"

# [profile.dev]
# warnings = "deny"

[profile.release]
warnings = "deny"
